<?php

namespace Magnum\Output\Render;

use Phrender\Engine;

class TwoStage
	extends Engine
{
	/**
	 * @var int the level of rendering we are currently at
	 */
	private $level = 0;

	/**
	 * @var string the name of the layout to use
	 */
	protected $layout;

	/**
	 * Changes the layout in use
	 *
	 * @param string $layout
	 * @return $this
	 */
	public function changeLayout($layout)
	{
		$this->layout = $layout;

		return $this;
	}

	/**
	 * Overrides the parent render to handle layouts
	 *
	 * @param      $template
	 * @param null $data
	 * @return string
	 */
	public function render($template, $data = null)
	{
		$this->level++;
		$output = parent::render("views/{$template}", $data); // TODO: Change the autogenerated stub

		if (isset($this->layout) && --$this->level === 0) {
			return parent::render("layouts/{$this->layout}", ['content' => $output]);
		}

		return $output;
	}

	/**
	 * Loads the requested template
	 *
	 * @param $template
	 * @return \Interop\Output\Template
	 */
	protected function loadTemplate($template)
	{
		return $this->factory->load($template, $this);
	}
}